using System.Collections.Generic;
#if NETSTANDARD2_0_OR_GREATER || NET472_OR_GREATER || NET5_0_OR_GREATER
using System.Text.Json.Serialization;
#endif
using JanusRequest.ContentTranslator.Converters;

namespace JanusRequest
{
    /// <summary>
    /// Represents a problem details response following RFC 9457 (formerly RFC 7807).
    /// Provides a standardized way for HTTP APIs to communicate error information to clients.
    /// </summary>
#if NETSTANDARD2_0_OR_GREATER || NET472_OR_GREATER || NET5_0_OR_GREATER
    [JsonConverter(typeof(ProblemDetailsJsonConverter))]
#else
    [Newtonsoft.Json.JsonConverter(typeof(ProblemDetailsNewtonsoftJsonConverter))]
#endif
    public class ProblemDetails
    {
        /// <summary>
        /// A URI reference that identifies the problem type.
        /// When dereferenced, it should provide human-readable documentation for the problem type.
        /// Defaults to "about:blank" when not specified.
        /// </summary>
        public string Type { get; }

        /// <summary>
        /// A short, human-readable summary of the problem type.
        /// It should not change from occurrence to occurrence of the problem.
        /// </summary>
        public string Title { get; }

        /// <summary>
        /// The HTTP status code generated by the origin server for this occurrence of the problem.
        /// </summary>
        public int Status { get; }

        /// <summary>
        /// A human-readable explanation specific to this occurrence of the problem.
        /// </summary>
        public string Detail { get; }

        /// <summary>
        /// A URI reference that identifies the specific occurrence of the problem.
        /// </summary>
        public string Instance { get; }

        /// <summary>
        /// Additional members that extend the problem details beyond the standard fields.
        /// </summary>
        public IReadOnlyDictionary<string, ProblemExtensionNode> Extensions { get; }

        /// <summary>
        /// Initializes a new instance of the <see cref="ProblemDetails"/> class with full specification.
        /// </summary>
        /// <param name="type">A URI reference identifying the problem type.</param>
        /// <param name="title">A short summary of the problem type.</param>
        /// <param name="status">The HTTP status code.</param>
        /// <param name="detail">A human-readable explanation specific to this occurrence.</param>
        /// <param name="instance">A URI reference identifying this specific occurrence.</param>
        /// <param name="extensions">Additional extension members.</param>
        public ProblemDetails(
            string type,
            string title,
            int status,
            string detail = null,
            string instance = null,
            IReadOnlyDictionary<string, ProblemExtensionNode> extensions = null)
        {
            Type = type;
            Title = title;
            Status = status;
            Detail = detail;
            Instance = instance;
            Extensions = extensions;
        }
    }
}